server:
  port: 8081

spring:
  # logging
  logging:
    level:
      root: INFO
      web: DEBUG
      com:
        ggums:
          ggumtle: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web.cors: DEBUG
      org:
        hibernate:
          sql: debug

  #          # "?"로 표시되던 파라미터 값이 무엇인지 알 수 있습니다. - inhwa
  #          type:
  #            descriptor:
  #              sql: trace

  # DB Connection Info
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ninetofive?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ninetofive
    password: 98765

  # Jpa Setting
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: 
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  #        show_sql: true  # DB로 날리는 쿼리를 출력합니다. - inhwa

  # jwt setting
  jwt:
    secret:
      access: bucket_access_token
      refresh: bucket_refresh_token
      develop_dummy_1: bmluZXRvZml2ZeyEnOykgO2YuA
      develop_dummy_2: bmluZXRvZml2ZeyLoOywveyXvQ
      develop_dummy_3: bmluZXRvZml2ZeydtOyasOyEsQ
      develop_dummy_4: bmluZXRvZml2ZeydtOybkOyjvA
      develop_dummy_5: bmluZXRvZml2ZeyghOyngO2ZmA
      develop_dummy_6: bmluZXRvZml2ZeyhsOyduO2ZlA

  # Redis setting
  data:
    redis:
      port: 6379
      host: localhost
      address: redis://127.0.0.1:6379

  # Java Mail Sender Setting
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Web Address
  web:
    baseUrl: http://localhost:8081

# Swagger
springdoc:
  packages-to-scan: com.ggums.ggumtle.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    info:
      title: GGUMTLE API Server
      description: NineToFive API Server
      version: 0.0.1
